updated flake, moved home manager to follow unstable, hopefully works on raspberry pi
so because of a potential version mismatch when running on raspberry pi
```
       error: attribute 'genAttrs'' missing
       at
/nix/store/cm63zyz90mzc5dcd61502i2mwqa75pyf-source/modules/misc/qt.nix:294:13:
          293|     }
          294|     // (lib.genAttrs' [ "qt5ct" "qt6ct" ] (
             |             ^
          295|       name:
       Did you mean one of genAttrs or getAttrs?
```

i moved home manager to follow unstable nix pkgs, hopefully this fixes
it